using System.Collections.Generic;

namespace Markyu.LastKernel
{
    public static partial class GameLocalization
    {
        private static readonly Dictionary<string, LocalizedTextEntry> TextEntries = new()
        {
            ["language.label"] = L("Language: {0}", "语言：{0}", "語言：{0}", "言語：{0}", "언어: {0}", "Langue : {0}", "Sprache: {0}", "Idioma: {0}"),
            ["language.chinese"] = L("Simplified Chinese", "简体中文", "簡體中文", "簡体字中国語", "중국어 간체", "chinois simplifie", "Vereinfachtes Chinesisch", "chino simplificado"),
            ["language.english"] = L("English", "英语", "英語", "英語", "영어", "anglais", "Englisch", "ingles"),
            ["language.traditionalChinese"] = L("Traditional Chinese", "繁体中文", "繁體中文", "繁体字中国語", "중국어 번체", "chinois traditionnel", "Traditionelles Chinesisch", "chino tradicional"),
            ["language.japanese"] = L("Japanese", "日语", "日語", "日本語", "일본어", "japonais", "Japanisch", "japones"),
            ["language.korean"] = L("Korean", "韩语", "韓語", "韓国語", "한국어", "coreen", "Koreanisch", "coreano"),
            ["language.french"] = L("French", "法语", "法語", "フランス語", "프랑스어", "francais", "Franzoesisch", "frances"),
            ["language.german"] = L("German", "德语", "德語", "ドイツ語", "독일어", "allemand", "Deutsch", "aleman"),
            ["language.spanish"] = L("Spanish", "西班牙语", "西班牙語", "スペイン語", "스페인어", "espagnol", "Spanisch", "espanol"),

            ["title.newGame"] = new("新游戏", "New Game"),
            ["title.loadGame"] = new("载入游戏", "Load Game"),
            ["title.options"] = new("运行设置", "Options"),
            ["title.quitGame"] = new("退出游戏", "Quit Game"),
            ["title.quitConfirmTitle"] = new("退出游戏", "Quit Game"),
            ["title.quitConfirmBody"] = new("确认要退出游戏吗？", "Are you sure you want to quit?"),
            ["title.versionDraft"] = new("版本：未发布", "Version: Unreleased"),
            ["title.loadHeader"] = new("读取存档", "Load Saves"),
            ["title.gameplayHeader"] = new("生存偏好设置", "Game Setup"),
            ["title.clearSaves"] = new("清除全部存档", "Delete All Saves"),
            ["title.noSaves"]    = new("暂无存档", "No saved games"),

            ["pause.header"] = new("已暂停", "Paused"),
            ["pause.resume"] = new("继续游戏", "Resume"),
            ["pause.backToTitle"] = new("返回主菜单", "Back to Title"),

            ["menu.quests"] = new("任务", "Quests"),
            ["menu.blueprints"] = new("蓝图", "Blueprints"),
            ["menu.infoPlaceholder"] = new(
                "<size=34>[情报面板]<size=30>\n信息会显示在这里。\n面板会根据文本长度自动调整尺寸。",
                "<size=34>[Intel Panel]<size=30>\nInformation appears here.\nThe panel resizes to fit the text."),

            ["ui.action"] = new("执行动作", "Run Action"),
            ["ui.footer"] = new("Last Kernel 堡垒街区试作 / 作者 Markyu", "Last Kernel Fortress District Prototype / Markyu"),
            ["ui.play"] = L("Deploy", "部署", "部署", "展開", "배치", "Deployer", "Einsetzen", "Desplegar"),
            ["ui.continue"] = L("Continue", "继续", "繼續", "続行", "계속", "Continuer", "Fortfahren", "Continuar"),
            ["ui.new_game"] = L("New Run", "新一轮", "新一輪", "新規ラン", "새 실행", "Nouvelle partie", "Neuer Lauf", "Nueva partida"),
            ["ui.settings"] = L("Settings", "设置", "設定", "設定", "설정", "Parametres", "Einstellungen", "Ajustes"),
            ["ui.quit"] = L("Quit", "退出", "退出", "終了", "종료", "Quitter", "Beenden", "Salir"),
            ["ui.back"] = L("Back", "返回", "返回", "戻る", "뒤로", "Retour", "Zurueck", "Atras"),
            ["ui.confirm"] = L("Confirm", "确认", "確認", "確定", "확인", "Confirmer", "Bestaetigen", "Confirmar"),
            ["ui.cancel"] = L("Cancel", "取消", "取消", "キャンセル", "취소", "Annuler", "Abbrechen", "Cancelar"),
            ["ui.apply"] = L("Apply", "应用", "套用", "適用", "적용", "Appliquer", "Anwenden", "Aplicar"),
            ["ui.language"] = L("Language", "语言", "語言", "言語", "언어", "Langue", "Sprache", "Idioma"),
            ["ui.audio"] = L("Audio", "音频", "音訊", "オーディオ", "오디오", "Audio", "Audio", "Audio"),
            ["ui.video"] = L("Video", "视频", "視訊", "ビデオ", "비디오", "Video", "Video", "Video"),
            ["ui.controls"] = L("Controls", "控制", "控制", "操作", "조작", "Commandes", "Steuerung", "Controles"),
            ["ui.credits"] = L("Credits", "制作名单", "製作名單", "クレジット", "크레딧", "Credits", "Credits", "Creditos"),

            ["menu.title"] = L("Last Kernel", "Last Kernel", "Last Kernel", "Last Kernel", "Last Kernel", "Last Kernel", "Last Kernel", "Last Kernel"),
            ["menu.subtitle"] = L("Hold the bunker. Stack the future.", "守住地堡，堆起未来。", "守住地堡，堆起未來。", "バンカーを守り、未来を積み上げろ。", "벙커를 지키고 미래를 쌓아 올리세요.", "Tenez le bunker. Empilez l avenir.", "Haltet den Bunker. Stapelt die Zukunft.", "Defiende el bunker. Apila el futuro."),
            ["menu.start_run"] = L("Start Run", "开始行动", "開始行動", "ラン開始", "실행 시작", "Lancer une partie", "Lauf starten", "Iniciar partida"),
            ["menu.load_run"] = L("Load Run", "载入行动", "載入行動", "ランをロード", "실행 불러오기", "Charger une partie", "Lauf laden", "Cargar partida"),
            ["menu.options"] = L("Options", "选项", "選項", "オプション", "옵션", "Options", "Optionen", "Opciones"),
            ["menu.exit"] = L("Exit", "离开", "離開", "終了", "나가기", "Quitter", "Verlassen", "Salir"),

            ["gameplay.day"] = L("Day", "白昼", "白晝", "昼", "낮", "Jour", "Tag", "Dia"),
            ["gameplay.night"] = L("Night", "黑夜", "黑夜", "夜", "밤", "Nuit", "Nacht", "Noche"),
            ["gameplay.wave"] = L("Wave", "波次", "波次", "ウェーブ", "공세", "Vague", "Welle", "Oleada"),
            ["gameplay.pause"] = L("Pause", "暂停", "暫停", "一時停止", "일시 정지", "Pause", "Pause", "Pausa"),
            ["gameplay.resume"] = L("Resume", "继续", "繼續", "再開", "재개", "Reprendre", "Fortsetzen", "Reanudar"),
            ["gameplay.speed_normal"] = L("Normal Speed", "正常速度", "正常速度", "通常速度", "보통 속도", "Vitesse normale", "Normales Tempo", "Velocidad normal"),
            ["gameplay.speed_fast"] = L("Fast Speed", "快速", "快速", "高速", "빠른 속도", "Vitesse rapide", "Schnelles Tempo", "Velocidad rapida"),
            ["gameplay.speed_pause"] = L("Paused", "已暂停", "已暫停", "停止中", "일시 정지됨", "En pause", "Pausiert", "Pausado"),
            ["gameplay.end_turn"] = L("End Turn", "结束回合", "結束回合", "ターン終了", "턴 종료", "Fin du tour", "Zug beenden", "Terminar turno"),
            ["gameplay.next_night"] = L("Next Night", "进入黑夜", "進入黑夜", "次の夜へ", "다음 밤", "Nuit suivante", "Naechste Nacht", "Siguiente noche"),

            ["card.worker"] = L("Worker", "工人", "工人", "作業員", "작업자", "Ouvrier", "Arbeiter", "Trabajador"),
            ["card.engineer"] = L("Engineer", "工程师", "工程師", "エンジニア", "기술자", "Ingenieur", "Ingenieur", "Ingeniero"),
            ["card.scrap"] = L("Scrap", "废料", "廢料", "スクラップ", "고철", "Ferraille", "Schrott", "Chatarra"),
            ["card.circuit"] = L("Circuit", "电路", "電路", "回路", "회로", "Circuit", "Schaltkreis", "Circuito"),
            ["card.power_core"] = L("Power Core", "能量核心", "能量核心", "パワーコア", "전력 코어", "Coeur d energie", "Energiekern", "Nucleo de energia"),
            ["card.food_ration"] = L("Food Ration", "口粮", "口糧", "食料配給", "식량 배급", "Ration", "Ration", "Racion"),
            ["card.shelter"] = L("Shelter", "避难所", "避難所", "シェルター", "대피소", "Abri", "Schutzraum", "Refugio"),
            ["card.turret"] = L("Turret", "炮塔", "砲塔", "タレット", "포탑", "Tourelle", "Geschuetz", "Torreta"),
            ["card.wall"] = L("Wall", "墙体", "牆體", "壁", "벽", "Mur", "Mauer", "Muro"),
            ["card.generator"] = L("Generator", "发电机", "發電機", "発電機", "발전기", "Generateur", "Generator", "Generador"),
            ["card.repair_drone"] = L("Repair Drone", "维修无人机", "維修無人機", "修理ドローン", "수리 드론", "Drone de reparation", "Reparaturdrohne", "Dron de reparacion"),
            ["card.signal_tower"] = L("Signal Tower", "信号塔", "訊號塔", "信号塔", "신호탑", "Tour de signal", "Signalturm", "Torre de senal"),

            ["resource.scrap"] = L("Scrap", "废料", "廢料", "スクラップ", "고철", "Ferraille", "Schrott", "Chatarra"),
            ["resource.energy"] = L("Energy", "能量", "能量", "エネルギー", "에너지", "Energie", "Energie", "Energia"),
            ["resource.food"] = L("Food", "食物", "食物", "食料", "식량", "Nourriture", "Nahrung", "Comida"),
            ["resource.morale"] = L("Morale", "士气", "士氣", "士気", "사기", "Moral", "Moral", "Moral"),
            ["resource.data"] = L("Data", "数据", "資料", "データ", "데이터", "Donnees", "Daten", "Datos"),
            ["resource.cores"] = L("Cores", "核心", "核心", "コア", "코어", "Coeurs", "Kerne", "Nucleos"),
            ["resource.population"] = L("Population", "人口", "人口", "人口", "인구", "Population", "Bevoelkerung", "Poblacion"),

            ["combat.incoming_wave"] = L("Wave inbound", "敌潮来袭", "敵潮來襲", "ウェーブ接近", "공세 접근 중", "Vague en approche", "Welle im Anflug", "Oleada entrante"),
            ["combat.enemy_breach"] = L("Breach detected", "发现突破口", "發現突破口", "侵入を検知", "침입 감지", "Breche detectee", "Durchbruch erkannt", "Brecha detectada"),
            ["combat.core_under_attack"] = L("Core under attack", "核心遭到攻击", "核心遭到攻擊", "コア攻撃中", "코어 공격받는 중", "Coeur attaque", "Kern unter Angriff", "Nucleo bajo ataque"),
            ["combat.victory"] = L("Victory", "胜利", "勝利", "勝利", "승리", "Victoire", "Sieg", "Victoria"),
            ["combat.defeat"] = L("Defeat", "失败", "失敗", "敗北", "패배", "Defaite", "Niederlage", "Derrota"),
            ["combat.repair_phase"] = L("Repair Phase", "维修阶段", "維修階段", "修理フェーズ", "수리 단계", "Phase de reparation", "Reparaturphase", "Fase de reparacion"),

            ["night.incursionTitle"] = new("夜间入侵", "Night Incursion"),
            ["night.startBody"] = new("{0}\n\n{1}\n\n部署了 {2} 名防守者，对抗 {3} 名敌人。", "{0}\n\n{1}\n\n{2} defender(s) deployed against {3} enemy unit(s)."),
            ["night.resultVictory"] = new("敌潮已击退", "Wave Repelled"),
            ["night.resultDefeat"] = new("防线被突破", "Defenses Breached"),
            ["night.undefendedTitle"] = new("无人防守", "Undefended"),
            ["night.undefendedBody"] = new("没有可用防守者。入侵未受阻拦地袭来。", "No defenders were available. The incursion struck unchallenged."),
            ["night.summaryWaveRepelled"] = new("敌潮已击退。已摧毁 {0}/{1} 名敌人。", "Wave repelled. {0}/{1} enemies destroyed."),
            ["night.summaryDefendersLost"] = new("损失 {0} 名防守者。", "{0} defender(s) lost."),
            ["night.summaryNoCasualties"] = new("无伤亡。", "No casualties."),
            ["night.summaryDefensesBreached"] = new("防线被突破。损失 {0}/{1} 名防守者。", "Defenses breached. {0}/{1} defender(s) lost."),
            ["night.summaryEnemiesDestroyedBeforeBreach"] = new("突破前摧毁了 {0}/{1} 名敌人。", "{0}/{1} enemies destroyed before breach."),
            ["night.laneHeader"] = new("夜间入侵", "NIGHT INCURSION"),
            ["night.laneVersus"] = new("对抗", "VS"),
            ["night.laneDefenders"] = new("防守者", "DEFENDERS"),
            ["night.laneEnemies"] = new("敌人", "ENEMIES"),
            ["night.laneDead"] = new("倒下", "DEAD"),
            ["night.waveLabel"] = new("第 {0} 波", "Wave {0}"),
            ["night.enemyCount"] = new("敌方：{0}", "Enemies: {0}"),
            ["night.speedNormal"] = new("正常", "Normal"),
            ["night.speedFast"] = new("快速", "Fast"),
            ["night.scrapReward"] = new("回收废料：{0}", "Scrap salvaged: {0}"),
            ["defeat.message"] = new("地堡已失守。", "The bunker has fallen."),

            // ── Night Battle Modal ─────────────────────────────────────────────────
            // Phase status labels
            ["night.modal.phase.prep"]     = L("PREP PHASE",    "准备阶段",  "準備階段",  "準備フェーズ", "준비 단계",   "PHASE PREP",    "VORBEREITUNGSPHASE", "FASE PREP"),
            ["night.modal.phase.battle"]   = L("COMBAT ACTIVE", "战斗进行中","戰鬥進行中","戦闘中",       "전투 진행 중","COMBAT EN COURS","KAMPF AKTIV",        "COMBATE ACTIVO"),
            ["night.modal.phase.victory"]  = L("VICTORY",       "胜利",      "勝利",      "勝利",         "승리",        "VICTOIRE",      "SIEG",               "VICTORIA"),
            ["night.modal.phase.defeat"]   = L("DEFEAT",        "防线失守",  "防線失守",  "防衛突破",     "방어선 붕괴", "DÉFAITE",       "NIEDERLAGE",         "DERROTA"),

            // Night header / counts
            ["night.modal.nightTitle"]     = new("第 {0} 夜",          "NIGHT {0}"),
            ["night.modal.incoming"]       = new("{0} 名敌人来袭",      "{0} ENEMIES INCOMING"),
            ["night.modal.enemiesRemaining"] = new("{0}/{1} 敌人剩余",    "{0}/{1} ENEMIES LEFT"),
            ["night.modal.units"]          = new("{0} 个单位",          "{0} UNITS"),
            ["night.modal.slotsStatus"]    = new("{0} / {1} 格位已分配", "{0} / {1} SLOTS FILLED"),

            // Threat
            ["night.modal.threat"]         = new("威胁等级：{0}", "THREAT: {0}"),
            ["night.modal.threat.low"]     = L("LOW",      "低",   "低",   "低",     "낮음", "FAIBLE",  "NIEDRIG",  "BAJO"),
            ["night.modal.threat.moderate"]= L("MODERATE", "中等", "中等", "中程度", "보통", "MODÉRÉ",  "MODERAT",  "MODERADO"),
            ["night.modal.threat.high"]    = L("HIGH",     "高",   "高",   "高",     "높음", "ÉLEVÉ",   "HOCH",     "ALTO"),
            ["night.modal.threat.critical"]= L("CRITICAL", "极危", "極危", "危機的", "위험", "CRITIQUE", "KRITISCH", "CRÍTICO"),

            // Gold display
            ["night.modal.gold"]           = new("◈ {0}", "◈ {0}"),

            // Result panel
            ["night.modal.result.win"]     = L("SYSTEM HELD",     "系统守住", "系統守住", "システム防衛成功", "시스템 유지", "SYSTÈME TENU",    "SYSTEM GEHALTEN",  "SISTEMA MANTENIDO"),
            ["night.modal.result.loss"]    = L("SYSTEM BREACHED", "系统失守", "系統失守", "システム突破",     "시스템 돌파", "SYSTÈME PERCÉ",   "SYSTEM VERLETZT",  "SISTEMA FALLADO"),
            ["night.modal.reward.title"]   = new("选择一张奖励卡", "Choose one reward card"),
            ["night.modal.reward.category"]= new("类型：{0}", "TYPE: {0}"),
            ["night.modal.reward.noDescription"] = new("回收所得的可用卡牌。", "Recovered usable card."),

            // Action buttons
            ["night.modal.btn.start"]      = L("[ START BATTLE ]",  "[ 开始战斗 ]", "[ 開始戰鬥 ]", "[ 戦闘開始 ]", "[ 전투 시작 ]", "[ LANCER LA BATAILLE ]", "[ KAMPF STARTEN ]",    "[ INICIAR BATALLA ]"),
            ["night.modal.btn.fast"]       = L("[ RESOLVE FAST ]",  "[ 快速结算 ]", "[ 快速結算 ]", "[ 高速解決 ]", "[ 빠른 해결 ]", "[ RÉSOUDRE VITE ]",      "[ SCHNELL LÖSEN ]",    "[ RESOLVER RÁPIDO ]"),
            ["night.modal.btn.autoDeploy"] = L("[ AUTO-FIGHT ]",    "[ 自动开战 ]", "[ 自動開戰 ]", "[ 自動開戰 ]", "[ 자동 전투 ]", "[ COMBAT AUTO ]",        "[ AUTO-KAMPF ]",       "[ AUTO-COMBATE ]"),
            ["night.modal.btn.return"]     = L("[ RETURN TO DAY ]", "[ 返回白天 ]", "[ 返回白天 ]", "[ 昼へ戻る ]", "[ 낮으로 복귀 ]","[ RETOUR AU JOUR ]",    "[ RÜCK ZUM TAG ]",     "[ VOLVER AL DÍA ]"),

            // Section headers
            ["night.modal.section.enemy"]    = L("ENEMY LINE",          "敌方战线",   "敵方戰線",   "敵戦線",   "적 전선",     "LIGNE ENNEMIE",   "FEINDREIHE",       "LÍNEA ENEMIGA"),
            ["night.modal.section.colony"]   = L("COLONY LINE",         "殖民地战线", "殖民地戰線", "植民地戦線","식민지 전선", "LIGNE COLONIE",   "KOLONIEREIHE",     "LÍNEA COLONIA"),
            ["night.modal.section.defenders"]= L("AVAILABLE DEFENDERS", "可用防守者", "可用防守者", "利用可能な守護者","가용 수비자","DÉFENSEURS DISPOS.","VERFÜGBARE VERTEIDIGER","DEFENSORES DISPONIBLES"),
            ["night.modal.section.log"]      = L("COMBAT LOG",  "战斗日志", "戰鬥日誌", "戦闘ログ",   "전투 기록", "JOURNAL DE COMBAT", "KAMPFPROTOKOLL", "REGISTRO DE COMBATE"),
            ["night.modal.section.shop"]     = L("NIGHT SHOP",  "夜间商店", "夜間商店", "夜間ショップ","야간 상점", "BOUTIQUE DE NUIT",  "NACHTLADEN",     "TIENDA NOCTURNA"),

            // Hints
            ["night.modal.hint.assign"] = new("点击防守者，再点击格位以分配。", "Click a defender, then click a slot to assign."),
            ["night.modal.hint.shop"]   = new("用金币购买道具，点击道具再点击战士以使用。", "Buy items with gold. Click item, then click a fighter."),

            // Slot / unit labels
            ["night.modal.slot.front"] = L("FRONT", "前排", "前排", "最前列", "앞줄", "AVANT", "VORNE", "FRENTE"),
            ["night.modal.slot.n"]     = new("#{0}", "#{0}"),

            // Stats formats
            ["night.modal.stats.enemy"]   = new("攻击 {0}  生命 {1}", "ATK {0}  |  HP {1}"),
            ["night.modal.stats.fighter"] = new("攻击 {0}  生命 {1}", "ATK {0}  HP {1}"),

            // Combat log messages
            ["night.modal.log.begin"]       = new("第 {0} 夜开始。选择你的防守者。",       "Night {0} begins. Choose your defenders."),
            ["night.modal.log.noDefenders"] = new("警告：没有找到可用防守者。",             "WARNING: No eligible defenders found."),
            ["night.modal.log.battleStart"] = new("战斗开始。",                             "Battle commences."),
            ["night.modal.log.victoryLog"]  = new("殖民地度过了这一夜。",                   "Colony survived the night."),
            ["night.modal.log.defeatLog"]   = new("殖民地防线被突破。",                     "Colony defenses breached."),
            ["night.modal.log.undefended"]  = new("警告：无防守者出战——殖民地无防护。",     "WARNING: No defenders — colony is undefended."),
            ["night.modal.log.formation"]   = new("阵形锁定。战斗即将开始。",               "Formation locked. Initiating combat."),
            ["night.modal.log.fastResolve"] = new("快速结算模式已激活。",                   "Fast resolve activated."),
            ["night.modal.log.autoDeploy"]  = new("已自动部署全部可用防守者。",             "Auto-deployed all available defenders."),
            ["night.modal.log.rewardRequired"] = new("先选择一张奖励卡。",                   "Choose a reward card first."),
            ["night.modal.log.rewardSelected"] = new("已选择奖励：{0}。",                    "Reward selected: {0}."),
            ["night.modal.log.slotMoved"]    = new("已将 {0} 移动到槽位 {1}。",              "Moved {0} to slot {1}."),
            ["night.modal.log.noGold"]      = new("金币不足。需要 {0}，现有 {1}。",         "Not enough gold. Need {0}, have {1}."),
            ["night.modal.log.noSlot"]      = new("没有空余槽位给雇佣卫兵。",               "No empty slot available for Hired Guard."),
            ["night.modal.log.purchased"]   = new("已购买：{0}。",                          "Purchased: {0}."),
            ["night.modal.log.itemSelected"]= new("已选择：{0}。点击战士以使用。",          "Selected: {0}. Click a fighter to apply."),
            ["night.modal.log.itemApplied"] = new("已将 {0} 用于 {1}。",                    "Applied {0} to {1}."),
            ["night.modal.log.missed"]      = new("{0} 攻击 {1}——未命中。",                 "{0} attacks {1} — MISSED."),
            ["night.modal.log.hit"]         = new("{0} 对 {1} 造成 {2}{3} 点伤害。",         "{0} hits {1} for {2}{3}."),
            ["night.modal.log.crit"]        = new("【暴击】",                               " [CRIT]"),
            ["night.modal.log.unitDied"]    = new("{0} 已倒下。",                            "{0} is destroyed."),

            // Night shop — effect descriptions (fallback when SO has no custom description)
            ["night.shop.effect.addAttack"]    = new("+{0} 攻击",                        "+{0} ATK"),
            ["night.shop.effect.addMaxHealth"] = new("+{0} 最大血量",                    "+{0} Max HP"),
            ["night.shop.effect.fullHeal"]     = new("恢复全部血量",                      "Restore full HP"),
            ["night.shop.effect.hireGuard"]    = new("雇佣临时战士 {0}攻/{1}血",         "Temp fighter {0}ATK/{1}HP"),

            // Night shop — default runtime item names and descriptions
            ["night.shop.default.scrapBlade.name"]    = new("废铁刀",              "Scrap Blade"),
            ["night.shop.default.scrapBlade.desc"]    = new("为战士 +1 攻击",      "+1 ATK to fighter"),
            ["night.shop.default.platedVest.name"]    = new("钢板背心",            "Plated Vest"),
            ["night.shop.default.platedVest.desc"]    = new("为战士 +3 最大血量",  "+3 Max HP to fighter"),
            ["night.shop.default.energyDrink.name"]   = new("能量饮料",            "Energy Drink"),
            ["night.shop.default.energyDrink.desc"]   = new("+1 攻击（此战有效）", "+1 ATK this battle"),
            ["night.shop.default.repairKit.name"]     = new("急救包",              "Repair Kit"),
            ["night.shop.default.repairKit.desc"]     = new("将战士恢复至满血",    "Restore fighter to full HP"),
            ["night.shop.default.hiredGuard.name"]    = new("雇佣卫兵",            "Hired Guard"),
            ["night.shop.default.hiredGuard.desc"]    = new("添加临时战士 3攻/6血","Add temp 3ATK/6HP fighter"),

            // Procedural wave / enemy names (used with GetOptional)
            ["night.enemy.scavenger"]          = new("拾荒者",             "Scavenger"),
            ["night.wave.procedural.name"]     = new("夜间突袭",           "Nightly Incursion"),
            ["night.wave.procedural.flavor"]   = new("拾荒者趁着黑夜探查防线。", "Scavengers probe the perimeter under cover of dark."),

            ["stat.maxHealth"] = new("最大生命值", "Max Health"),
            ["stat.attack"] = new("攻击", "Attack"),
            ["stat.defense"] = new("防御", "Defense"),
            ["stat.attackSpeed"] = new("攻击速度", "Attack Speed"),
            ["stat.accuracy"] = new("命中率", "Accuracy"),
            ["stat.dodge"] = new("闪避", "Dodge"),
            ["stat.criticalChance"] = new("暴击率", "Crit. Chance"),
            ["stat.criticalMultiplier"] = new("暴击倍率", "Crit. Multiplier"),

            ["event.blackout"] = L("Blackout", "断电", "斷電", "停電", "정전", "Panne noire", "Stromausfall", "Apagon"),
            ["event.system_glitch"] = L("System Glitch", "系统故障", "系統故障", "システム異常", "시스템 오류", "Defaut systeme", "Systemstoerung", "Fallo del sistema"),
            ["event.supply_drop"] = L("Supply Drop", "补给投放", "補給投放", "補給投下", "보급 투하", "Largage de ravitaillement", "Nachschubabwurf", "Entrega de suministros"),
            ["event.supply_cache"] = L("Supply Cache", "补给藏匿点", "補給藏匿點", "補給庫", "보급품 은닉처", "Cache de ravitaillement", "Nachschublager", "Almacen de suministros"),
            ["event.refugees_arrive"] = L("Refugees Arrive", "难民抵达", "難民抵達", "避難民到着", "피난민 도착", "Refugies arrives", "Fluechtlinge kommen an", "Llegan refugiados"),
            ["event.machine_whispers"] = L("Machine Whispers", "机器低语", "機器低語", "機械のささやき", "기계의 속삭임", "Murmures de machine", "Maschinenfluestern", "Susurros de maquina"),

            ["settings.language_changed"] = L("Language changed", "语言已更改", "語言已變更", "言語を変更しました", "언어 변경됨", "Langue changee", "Sprache geaendert", "Idioma cambiado"),
            ["settings.restart_required"] = L("Restart required", "需要重启", "需要重新啟動", "再起動が必要", "재시작 필요", "Redemarrage requis", "Neustart erforderlich", "Reinicio requerido"),
            ["settings.fullscreen"] = L("Fullscreen", "全屏", "全螢幕", "全画面", "전체 화면", "Plein ecran", "Vollbild", "Pantalla completa"),
            ["settings.resolution"] = L("Resolution", "分辨率", "解析度", "解像度", "해상도", "Resolution", "Aufloesung", "Resolucion"),
            ["settings.master_volume"] = L("Master Volume", "主音量", "主音量", "マスター音量", "마스터 볼륨", "Volume principal", "Gesamtlautstaerke", "Volumen maestro"),
            ["settings.music_volume"] = L("Music Volume", "音乐音量", "音樂音量", "音楽音量", "음악 볼륨", "Volume musique", "Musiklautstaerke", "Volumen de musica"),
            ["settings.sfx_volume"] = L("SFX Volume", "音效音量", "音效音量", "効果音量", "효과음 볼륨", "Volume SFX", "SFX Lautstaerke", "Volumen SFX"),

            ["tooltip.morale"] = L("Morale keeps the bunker moving.", "士气让地堡继续运转。", "士氣讓地堡繼續運轉。", "士気はバンカーを動かし続けます。", "사기는 벙커를 계속 움직입니다.", "Le moral maintient le bunker.", "Moral haelt den Bunker am Laufen.", "La moral mantiene el bunker activo."),
            ["tooltip.energy"] = L("Energy powers machines and defenses.", "能量驱动机器和防线。", "能量驅動機器和防線。", "エネルギーは機械と防衛を動かします。", "에너지는 기계와 방어 시설을 가동합니다.", "L energie alimente machines et defenses.", "Energie versorgt Maschinen und Verteidigung.", "La energia alimenta maquinas y defensas."),
            ["tooltip.scrap"] = L("Scrap builds almost everything.", "废料几乎能建造一切。", "廢料幾乎能建造一切。", "スクラップはほぼ全ての材料です。", "고철은 거의 모든 것을 만듭니다.", "La ferraille sert presque partout.", "Schrott baut fast alles.", "La chatarra construye casi todo."),
            ["tooltip.night_phase"] = L("Night brings pressure and hostile waves.", "黑夜会带来压力和敌潮。", "黑夜會帶來壓力和敵潮。", "夜は圧力と敵の波を運びます。", "밤에는 압박과 적 공세가 옵니다.", "La nuit apporte pression et vagues hostiles.", "Die Nacht bringt Druck und feindliche Wellen.", "La noche trae presion y oleadas hostiles."),
            ["tooltip.stack_cards"] = L("Stack cards to combine workers resources and structures.", "堆叠卡牌来组合工人、资源与结构。", "堆疊卡牌來組合工人、資源與結構。", "カードを重ねて作業員、資源、施設を組み合わせます。", "카드를 쌓아 작업자와 자원 및 구조물을 결합하세요.", "Empilez les cartes pour combiner ouvriers ressources et structures.", "Stapelt Karten um Arbeiter Ressourcen und Bauten zu kombinieren.", "Apila cartas para combinar trabajadores recursos y estructuras."),
            ["tooltip.defense_grid"] = L("Place defenses to hold the grid.", "布置防御来守住网格。", "佈置防禦來守住網格。", "防衛を配置してグリッドを守ります。", "방어를 배치해 격자를 지키세요.", "Placez des defenses pour tenir la grille.", "Platziert Verteidigung um das Raster zu halten.", "Coloca defensas para sostener la cuadricula."),

            ["common.confirmButton"] = new("确认",    "Confirm"),
            ["common.cancelButton"]  = new("取消",    "Cancel"),
            ["common.applyButton"]   = new("应用",    "Apply"),
            ["common.closeButton"]   = new("关闭",    "Close"),
            ["common.resetButton"]   = new("重置全部", "Reset All"),
            ["options.language.title"] = L("选择语言", "Select Language", "選擇語言", "言語を選択", "언어 선択", "Choisir la langue", "Sprache wahlen", "Seleccionar idioma"),
            ["common.loadButton"]    = new("读取",    "Load"),
            ["common.deleteButton"]  = new("删除",    "Delete"),

            ["options.header"] = L("Options", "选项", "選項", "オプション", "옵션", "Options", "Optionen", "Opciones"),
            ["options.sfx"] = new("音效 {0}%", "SFX {0}%"),
            ["options.bgm"] = new("背景音乐 {0}%", "BGM {0}%"),
            ["options.uiScale"]        = new("界面文字大小", "UI Scale"),
            ["options.uiScale.label"]  = new("界面文字大小：{0}", "UI Scale: {0}"),
            ["options.uiScale.xsmall"] = L("Tiny",       "极小", "極小", "極小", "아주 작음", "Minuscule", "Winzig",    "Muy pequeño"),
            ["options.uiScale.small"]  = L("Small",      "小",   "小",   "小",   "작음",   "Petit",      "Klein",     "Pequeño"),
            ["options.uiScale.medium"] = L("Medium",     "中",   "中",   "中",   "보통",   "Moyen",      "Mittel",    "Mediano"),
            ["options.uiScale.large"]  = L("Large",      "大",   "大",   "大",   "큼",     "Grand",      "Groß",      "Grande"),
            ["options.uiScale.xlarge"] = L("Super Large","特大", "特大", "特大", "매우 큼","Très grand", "Sehr groß", "Muy grande"),
            ["options.resetTitle"] = new("重置系统设置？", "Reset Settings?"),
            ["options.resetBody"] = new(
                "这会把全部图形与音频参数恢复为默认值，且无法撤销。",
                "This resets all graphics and audio settings to their defaults and cannot be undone."),

            ["gameplay.dayDuration"]       = new("白昼时长：{0} 秒", "Day Length: {0}s"),
            ["gameplay.friendlyModeLabel"] = new("友好模式", "Friendly Mode"),
            ["gameplay.friendlyMode.on"]  = new("开启", "On"),
            ["gameplay.friendlyMode.off"] = new("关闭", "Off"),
            ["gameplay.friendlyOn"]  = new("（敌对目标不会出现）", "(No hostile targets will appear)"),
            ["gameplay.friendlyOff"] = new("（敌对目标可能出现）", "(Hostile targets may appear)"),

            ["gameplay.difficultyLabel"]         = new("难度",     "Difficulty"),
            ["gameplay.difficulty.easy"]         = L("Easy",    "简单", "簡單", "かんたん",   "쉬움",   "Facile",    "Einfach",      "Facil"),
            ["gameplay.difficulty.normal"]       = L("Normal",  "普通", "普通", "ふつう",     "보통",   "Normal",    "Normal",       "Normal"),
            ["gameplay.difficulty.hard"]         = L("Hard",    "困难", "困難", "むずかしい", "어려움", "Difficile", "Schwer",       "Dificil"),

            ["gameplay.startResourcesLabel"]     = new("起始资源", "Starting Resources"),
            ["gameplay.startResources.minimal"]  = L("Minimal",  "最少", "最少", "最小", "최소", "Minimal",   "Minimal",      "Minimo"),
            ["gameplay.startResources.standard"] = L("Standard", "标准", "標準", "標準", "기본", "Standard",  "Standard",     "Estandar"),
            ["gameplay.startResources.generous"] = L("Generous", "充裕", "充裕", "豊富", "풍족", "Genereux",  "Grosszuegig",  "Generoso"),

            ["save.clearTitle"] = new("清除全部存档？", "Delete All Saves?"),
            ["save.clearBody"] = new(
                "确认要删除全部存档吗？\n此操作无法撤销。",
                "Are you sure you want to delete all save files?\nThis action cannot be undone."),
            ["save.deleteTitle"] = new("删除存档？", "Delete Save?"),
            ["save.deleteBody"] = new(
                "确认要删除 {0} 号存档吗？\n此操作无法撤销。",
                "Are you sure you want to delete save slot {0}?\nThis action cannot be undone."),
            ["save.slotLabel"] = new("[存档 {0:D3}] {1}{2}", "[Slot {0:D3}] {1}{2}"),
            ["save.progressSuffix"] = new(" ({0}%)", " ({0}%)"),
            ["save.lastSaved"] = new("\n上次保存：{0}", "\nLast Saved: {0}"),

            ["day.placeholder"] = new("第 N 天", "Day N"),
            ["day.current"] = new("第 {0} 天", "Day {0}"),

            ["hud.day"]         = L("DAY",   "白昼", "白晝", "昼",   "낮",    "JOUR",  "TAG",    "DÍA"),
            ["hud.night"]       = L("NIGHT", "夜间", "夜間", "夜",   "밤",    "NUIT",  "NACHT",  "NOCHE"),
            ["hud.startNight"]  = L("Start Night", "开始夜间", "開始夜間", "夜開始", "밤 시작", "Début de nuit", "Nacht beginnen", "Iniciar noche"),
            ["hud.wave"]        = L("Night {0}",   "第 {0} 夜", "第 {0} 夜", "夜 {0}", "밤 {0}", "Nuit {0}", "Nacht {0}", "Noche {0}"),
            ["hud.baseHP"]      = L("HP {0}/{1}", "HP {0}/{1}", "HP {0}/{1}", "HP {0}/{1}", "HP {0}/{1}", "HP {0}/{1}", "HP {0}/{1}", "HP {0}/{1}"),
            ["hud.enemies"]     = L("Enemies {0}/{1}", "敌人 {0}/{1}", "敵人 {0}/{1}", "敵 {0}/{1}", "적 {0}/{1}", "Ennemis {0}/{1}", "Feinde {0}/{1}", "Enemigos {0}/{1}"),
            ["hud.nutrition"]   = L("{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}"),
            ["hud.currency"]    = L("{0}",     "{0}",     "{0}",     "{0}",     "{0}",     "{0}",     "{0}",     "{0}"),
            ["hud.cards"]       = L("{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}", "{0}/{1}"),
            ["hud.pace.paused"]    = L("■ 0×",    "■ 0×",    "■ 0×",    "■ 0×",    "■ 0×",    "■ 0×",    "■ 0×",    "■ 0×"),
            ["hud.pace.normal"]    = L("▶ 1×",    "▶ 1×",    "▶ 1×",    "▶ 1×",    "▶ 1×",    "▶ 1×",    "▶ 1×",    "▶ 1×"),
            ["hud.pace.fast"]      = L("▶▶ 2×",   "▶▶ 2×",   "▶▶ 2×",   "▶▶ 2×",   "▶▶ 2×",   "▶▶ 2×",   "▶▶ 2×",   "▶▶ 2×"),
            ["hud.pace.veryffast"] = L("▶▶▶ 3×",  "▶▶▶ 3×",  "▶▶▶ 3×",  "▶▶▶ 3×",  "▶▶▶ 3×",  "▶▶▶ 3×",  "▶▶▶ 3×",  "▶▶▶ 3×"),

            ["common.on"]  = L("On",  "开",  "開",  "オン",  "켜짐",  "Activé",    "Ein",  "Activado"),
            ["common.off"] = L("Off", "关",  "關",  "オフ",  "꺼짐",  "Désactivé", "Aus",  "Desactivado"),

            ["daycycle.dayEndedTitle"] = new("第 {0} 天结束", "Day {0} Complete"),
            ["daycycle.dayEndedBody"] = new("街区需要补充口粮。", "The district needs rations."),
            ["daycycle.dayEndedAction"] = new("分发口粮", "Distribute Rations"),
            ["daycycle.feedingTitle"] = new("正在分发口粮", "Distributing Rations"),
            ["daycycle.feedingBody"] = new("正在为街区居民派发补给。", "Delivering supplies to the district residents."),
            ["daycycle.cleanupTitle"] = new("清理超载库存", "Reduce Overload"),
            ["daycycle.cleanupBody"] = new(
                "你还需要处理 {0} 张超额卡牌，系统才会推进到下一循环。",
                "You still need to remove {0} excess cards before the next cycle can begin."),
            ["daycycle.nightDefeatTitle"]  = new("殖民地遭到攻击",          "Colony Attacked"),
            ["daycycle.nightDefeatBody"]   = new("防线已被突破。士气目前为 {0}。在下次入侵前重建防御。", "The perimeter was breached. Morale is now {0}. Rebuild your defenses before the next incursion."),
            ["daycycle.nightDefeatAction"] = new("重建防御",                 "Rebuild"),
            ["daycycle.moraleCollapseTitle"] = new("殖民地已溃散",           "Colony Abandoned"),
            ["daycycle.moraleCollapseBody"]  = new("士气归零。殖民地已四散，再无值得守护之物。", "Morale has reached zero. The colony has dispersed — nothing remains worth defending."),

            ["daycycle.dayStartedTitle"] = new("第 {0} 天开始", "Day {0} Begins"),
            ["daycycle.dayStartedBody"] = new("街区节点已重新联机。", "District links are back online."),
            ["daycycle.dayStartedAction"] = new("启动新一天", "Start New Day"),
            ["daycycle.gameOverTitle"] = new("街区失守", "District Lost"),
            ["daycycle.gameOverBody"] = new("你已经没有任何可用人员了。", "No surviving Recruits remain."),
            ["daycycle.gameOverAction"] = new("返回标题", "Return to Title"),

            ["graphics.resolution"] = new("分辨率 {0}x{1}", "Resolution {0}x{1}"),
            ["graphics.fullscreen.windowed"] = new("显示模式 窗口化", "Display Windowed"),
            ["graphics.fullscreen.fullscreen"] = new("显示模式 全屏", "Display Fullscreen"),
            ["graphics.vsync.off"] = new("垂直同步 关闭", "VSync Off"),
            ["graphics.vsync.on"] = new("垂直同步 开启", "VSync On"),
            ["graphics.vsync.half"] = new("垂直同步 半速", "VSync Half Rate"),
            ["graphics.vsync.unknown"] = new("垂直同步 未知", "VSync Unknown"),
            ["graphics.fps.unlimited"] = new("帧率上限 不限", "FPS Cap Unlimited"),
            ["graphics.fps.capped"] = new("帧率上限 {0}", "FPS Cap {0}"),
            ["graphics.shadow.quality"] = new("阴影质量 {0}", "Shadows {0}"),
            ["graphics.shadow.off"] = new("关闭", "Off"),
            ["graphics.shadow.low"] = new("低", "Low"),
            ["graphics.shadow.medium"] = new("中", "Medium"),
            ["graphics.shadow.high"] = new("高", "High"),
            ["graphics.shadow.ultra"] = new("超高", "Ultra"),
            ["graphics.shadow.unknown"] = new("未知", "Unknown"),

            ["trade.price"] = new("价格：{0}", "Price: {0}"),
            ["trade.collectionComplete"] = new("<color=#FFD700>已完全解锁</color>", "<color=#FFD700>Fully Unlocked</color>"),
            ["trade.collectionProgress"] = new("已收录：\n{0}/{1}", "Collected:\n{0}/{1}"),
            ["trade.vendorHeader"] = new("卡包贩卖终端", "Pack Vendor"),
            ["trade.vendorBody"] = new("在这里可以购买 {0}。", "Buy {0} here."),
            ["trade.buyerHeader"] = new("卡牌回收终端", "Card Recycler"),
            ["trade.buyerBody"] = new("把可出售的卡牌拖到这里，换取信用点。", "Drag sellable cards here to exchange them for Credits."),
            ["trade.packUnlocked"] = new("新卡包已解锁", "New Pack Unlocked"),
            ["trade.sellStatic"] = new("出售", "Sell"),
            ["trade.expansionTitle"] = new("扩建", "Expand"),
            ["trade.expansionHeader"] = new("街区扩建终端", "District Expansion"),
            ["trade.expansionBody"] = new("拖入信用点，为街区棋盘购买一行新的可用区域。还需：{0}。", "Drag Credits here to buy a new district board row. Remaining: {0}."),
            ["trade.expansionProgress"] = new("扩建行：\n{0}/{1}", "Rows:\n{0}/{1}"),
            ["trade.expansionComplete"] = new("<color=#FFD700>空间已满</color>", "<color=#FFD700>Fully Expanded</color>"),
            ["trade.expansionCompleteBody"] = new("街区棋盘已经扩建到当前上限。", "The district board has reached its current expansion limit."),

            ["quest.progress"]        = new("进度：{0} / {1}", "Progress: {0} / {1}"),
            ["quest.footer.progress"] = new("任务：{0} / {1}", "Quests: {0} / {1}"),
            ["menu.quests.empty"]     = L("No active quests.",         "暂无激活任务",      "暫無激活任務",      "クエストなし",           "활성 퀘스트 없음",   "Aucune quête active.",     "Keine aktiven Aufgaben.",  "Sin misiones activas."),
            ["menu.recipes.empty"]    = L("No recipes discovered yet.","尚未发现任何配方。", "尚未發現任何配方。", "レシピ未発見。",         "레시피 미발견.",     "Aucune recette découverte.","Noch keine Rezepte.",       "Ninguna receta descubierta."),
            ["recipe.no_ingredients"] = L("No ingredients required.",  "无需材料。",        "無需材料。",        "材料不要。",             "재료 불필요.",       "Aucun ingrédient.",        "Keine Zutaten.",            "Sin ingredientes."),

            ["quest.group.新手引导"] = new("新手引导", "Beginner's Guide"),
            ["quest.group.异界升格"] = new("异界升格", "Otherworldly Ascension"),
            ["quest.group.战斗训练"] = new("战斗训练", "Combat Training"),
            ["quest.group.殖民进阶"] = new("殖民进阶", "Settlement Advancement"),
            ["quest.group.后勤炊事"] = new("后勤炊事", "Logistics & Supplies"),
            ["quest.group.区域探索"] = new("区域探索", "Area Exploration"),
            ["quest.group.海岛基础"] = new("海岛基础", "Island Basics"),

            ["recipe.blueprint"] = new("蓝图：{0}", "Blueprint: {0}"),
            ["recipe.unknown"] = new("蓝图：未知", "Blueprint: Unknown"),
            ["recipe.category.misc"] = new("杂项", "Misc"),
            ["recipe.category.gathering"] = new("回收", "Salvage"),
            ["recipe.category.construction"] = new("建造", "Construction"),
            ["recipe.category.cooking"] = new("烹饪", "Cooking"),
            ["recipe.category.forging"] = new("制造", "Fabrication"),
            ["recipe.category.refining"] = new("加工", "Refining"),
            ["recipe.category.husbandry"] = new("管控", "Containment"),

            ["card.timeLeft"] = new("剩余时间：{0:F1} 秒", "Time Left: {0:F1}s"),
            ["card.stackHeader"] = new("卡牌堆", "Stack of Cards"),
            ["card.health"] = new("生命值 ({0}/{1})", "Health ({0}/{1})"),
            ["card.statLine"] = new("{0}：{1}", "{0}: {1}"),
            ["card.section.lore"] = new("现场记录", "Field Notes"),
            ["card.section.visibleStats"] = new("可见指标", "Visible Stats"),
            ["card.section.hiddenStats"] = new("隐藏系统", "Hidden Systems"),
            ["card.section.economy"] = new("后勤价值", "Logistics Value"),
            ["card.hidden.combatType"] = new("战斗协议：{0}", "Combat Protocol: {0}"),
            ["card.sell"]           = L("Sell: {0} cr",     "出售：{0} 信用点", "出售：{0} 信用點", "売却：{0}",     "판매：{0}",    "Vente : {0}",       "Verkauf: {0}",        "Venta: {0}"),
            ["card.nutritionValue"] = L("Food: {0}",        "食物：{0}",       "食物：{0}",       "食料：{0}",    "식량：{0}",    "Aliment : {0}",     "Nahrung: {0}",        "Alimento: {0}"),
            ["card.usesLeft"]       = L("{0} uses",         "剩余 {0} 次",     "剩餘 {0} 次",     "残り {0} 回",  "잔여 {0} 회",  "{0} util. rest.",   "Noch {0}×",           "{0} usos"),
            ["card.category.none"]       = new("未分类", "Unclassified"),
            ["card.category.resource"]   = new("资源", "Resource"),
            ["card.category.character"]  = new("人员", "Operator"),
            ["card.category.consumable"] = new("补给", "Consumable"),
            ["card.category.material"]   = new("材料", "Material"),
            ["card.category.equipment"]  = new("装备", "Equipment"),
            ["card.category.structure"]  = new("设施", "Structure"),
            ["card.category.currency"]   = new("信用点", "Currency"),
            ["card.category.recipe"]     = new("蓝图", "Blueprint"),
            ["card.category.mob"]        = new("威胁体", "Threat"),
            ["card.category.area"]       = new("区域", "Area"),
            ["card.category.valuable"]   = new("贵重品", "Valuable"),
            ["card.combatType.none"]   = new("无", "None"),
            ["card.combatType.melee"]  = new("近战", "Melee"),
            ["card.combatType.ranged"] = new("远程", "Ranged"),
            ["card.combatType.magic"]  = new("异常", "Anomaly"),
            ["card.lore.default"] = new("这张卡被记录进堡垒街区的临时库存。它的价值不只在数字上，也在它能让下一次白天多撑一口气。", "Filed into the Fortstack inventory. Its value is not just the number on the face; it is one more margin of control before the next night pushes back."),
            ["card.lore.resource"] = new("边缘区回收来的基础资源，带着灰尘、旧编号和一点还能继续运转的希望。用于把混乱重新压成可管理的物资。", "A recovered base resource from the perimeter, tagged with old serials and just enough integrity to matter. Use it to turn disorder back into supply."),
            ["card.lore.character"] = new("幸存者不是单位格里的图标，而是防线里会疲惫、会犯错、也会在最后一刻顶住压力的人。保护他们，夜晚才有前排。", "A survivor is not just an icon in a slot. They tire, panic, improvise, and sometimes hold the line when the plan has already failed. Protect them; they are your front row after dark."),
            ["card.lore.consumable"] = new("能立刻消耗的补给品。它不会赢下整场战争，但它经常决定一个白天是否还能继续推进。", "A consumable supply piece. It will not win the whole war, but it often decides whether the current day has enough breath left to move."),
            ["card.lore.material"] = new("加工前的材料，适合进炉、进台、进任何还没完全坏掉的生产链。小而粗糙，但会成为更大的东西。", "Raw material for benches, rigs, and whatever production chain still answers when powered. Small, rough, and waiting to become leverage."),
            ["card.lore.equipment"] = new("装备会改变一个人的战斗轮廓：出手速度、容错、防线角色。别只看攻击力，也看它让谁活到第二轮。", "Equipment changes a fighter's silhouette: tempo, tolerance, and role in the line. Do not only read attack; read who survives into the second exchange."),
            ["card.lore.structure"] = new("设施是白天的骨架。建成以后，它会把一次性的收益变成可重复的制度。", "A structure is the skeleton of the day. Once built, it turns one-off gains into repeatable procedure."),
            ["card.lore.currency"] = new("信用点是压缩后的选择权。夜市、交易、临时雇佣都认它，但它不会替你挡刀。", "Currency is compressed agency. Shops, trades, and hired help all respect it, but it will not stand in the front slot for you."),
            ["card.lore.recipe"] = new("蓝图是记忆的另一种形态：有人曾经知道怎么把碎片变成工具，现在你也可以。", "A blueprint is memory in mechanical form: someone once knew how to turn scraps into tools, and now the colony can know it again."),
            ["card.lore.mob"] = new("威胁体的行为不稳定，但并非毫无规律。观察它的速度、命中和暴击倾向，才能让防线少付代价。", "A threat is unstable, not unknowable. Read its tempo, accuracy, and burst potential if you want the line to pay less for contact."),
            ["card.lore.area"] = new("区域代表新的风险边界。进入之前先准备补给，离开之后记得清点损失。", "An area marks a new boundary of risk. Stock before entry, count losses after return."),
            ["card.lore.valuable"] = new("贵重物资常常没有直接用途，却能打开被锁住的路线、交易和未来。别急着卖掉所有秘密。", "Valuables rarely look practical at first glance. They open locked routes, trades, and futures. Do not sell every secret too early."),
            ["night.modal.reward.stats.combat"] = new("攻击 {0}  /  生命 {1}  /  防御 {2}", "ATK {0}  /  HP {1}  /  DEF {2}"),
            ["night.modal.reward.stats.utility"] = new("{0}  /  出售 {1}", "{0}  /  SELL {1}"),
            ["quest.completed"]     = L("Completed",        "已完成",          "已完成",          "達成",         "완료",         "Complété",          "Abgeschlossen",       "Completado"),

            ["placeholder.packName"] = new("卡包名称", "Pack Name"),
            ["placeholder.cardName"] = new("卡牌名称", "Card Name"),

            ["modal.title"] = new("操作确认", "Confirm Action"),
            ["modal.body"] = new("确认执行这项操作吗？\n执行后将立即生效。", "Confirm this action?\nIt will take effect immediately.")
        };

        private static readonly Dictionary<string, string> InspectorTextKeys = new()
        {
            ["执行动作"] = "ui.action",
            ["已暂停"] = "pause.header",
            ["第 N 天"] = "day.placeholder",
            ["继续游戏"] = "pause.resume",
            ["任务"] = "menu.quests",
            ["蓝图"] = "menu.blueprints",
            ["保存并返回标题"] = "pause.backToTitle",
            ["FortStack 赛博殖民试作 / 作者 Markyu"] = "ui.footer",
            ["Last Kernel 赛博殖民试作 / 作者 Markyu"] = "ui.footer",
            ["Last Kernel 堡垒街区试作 / 作者 Markyu"] = "ui.footer",
            ["选项"] = "options.header",
            ["[Delete]"] = "common.deleteButton",
            ["[Load]"] = "common.loadButton",
            ["[取消]"] = "common.cancelButton",
            ["操作确认"] = "modal.title",
            ["确认执行这项操作吗？\n执行后将立即生效。"] = "modal.body",
            ["[确认]"] = "common.confirmButton",
            ["版本：未发布"] = "title.versionDraft",
            ["读取存档"] = "title.loadHeader",
            ["生存偏好设置"] = "title.gameplayHeader",
            ["[清除全部存档]"] = "title.clearSaves",
            ["退出游戏"] = "title.quitGame",
            ["载入游戏"] = "title.loadGame",
            ["新游戏"] = "title.newGame",
            ["Pack Name"] = "placeholder.packName",
            ["Card Name"] = "placeholder.cardName",
            ["Sell"] = "trade.sellStatic",
            ["<size=34>[情报面板]<size=30>\n信息会显示在这里。\n面板会根据文本长度自动调整尺寸。"] = "menu.infoPlaceholder"
        };

        private static LocalizedTextEntry L(
            string english,
            string simplifiedChinese,
            string traditionalChinese,
            string japanese,
            string korean,
            string french,
            string german,
            string spanish)
        {
            return new LocalizedTextEntry(
                english,
                simplifiedChinese,
                traditionalChinese,
                japanese,
                korean,
                french,
                german,
                spanish);
        }
    }
}
